# Created: 2025-01-10
# Updated: 2025-02-18

services:
  apache:
    build: .
    container_name: lamp-apache
    ports:
      - "8080:80"
    volumes:
      - dev-data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.4.4
    container_name: lamp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  dev-data:
